# Prometheus configuration for Flash USDT Bot monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Flash USDT Backend API
  - job_name: 'flashusdt-backend'
    static_configs:
      - targets: ['localhost:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node.js application metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']

  # Ethereum node metrics (if running own node)
  - job_name: 'ethereum-node'
    static_configs:
      - targets: ['localhost:8545']
    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 30s

  # Redis metrics (if using Redis)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:9121']

  # Nginx metrics (if using Nginx)
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['localhost:9113']